version: '3.8'

services:
  spark-worker:
    image: alexmerced/spark33-notebook
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
      # Oracle Object Storage credentials (same as master)
      - AWS_REGION=${ORACLE_REGION}
      - AWS_ACCESS_KEY_ID=${ORACLE_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ORACLE_SECRET_KEY}
      - AWS_S3_ENDPOINT=${ORACLE_ENDPOINT}
      - NESSIE_URI=${NESSIE_URI}
      - WAREHOUSE=${WAREHOUSE}
    volumes:
      - ./data:/home/jovyan/data
      - ./scripts:/home/jovyan/scripts
    networks:
      - lakehouse-network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 5G

networks:
  lakehouse-network:
    driver: bridge
