connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie-catalog.uri=http://lakehouse-nessie:19120/api/v1
iceberg.nessie-catalog.ref=main
iceberg.nessie-catalog.default-warehouse-dir=s3a://lakehouse-prod/warehouse
iceberg.file-format=PARQUET

# S3 Configuration using Hive properties (standard legacy inherited by Iceberg)
hive.s3.endpoint=https://bmcfe6z38foz.compat.objectstorage.ap-mumbai-1.oraclecloud.com
hive.s3.region=ap-mumbai-1
hive.s3.aws-access-key=962c9f862226831e4edea90cfcfafb8a8dffcd51
hive.s3.aws-secret-key=sd2rGU918DTmn35E4xJ8EV7BX2XUt7DkqC8v6WDNDUw=
hive.s3.path-style-access=true
hive.s3.ssl.enabled=true
